---
- name: Deploy Apache Docker Container
  hosts: localhost
  become: yes
  tasks:
    - name: Pull Apache Docker Image
      docker_image:
        name: httpd
        source: pull

    - name: Run Apache Container
      docker_container:
        name: apache_container
        image: httpd
        state: started
        ports:
          - "8080:80"
        networks:
          - name: apache_network

    - name: Create Apache Network
      docker_network:
        name: apache_network
        ipam_options:
          - subnet: 172.168.10.0/30

    - name: Copy Static Web Page to Container
      copy:
        src: /path/to/index.html
        dest: /usr/local/apache2/htdocs/index.html
      delegate_to: localhost
